SELECT_SUBSCRIBER = """
 SELECT *
 FROM SUBSCRIBER
"""

INSERT_SUBSCRIBER = """
 INSERT INTO SUBSCRIBER
 (USERNAME, INPUT_DATE)
 VALUES (?, DATETIME('NOW','LOCALTIME'))
"""

UPDATE_SUBSCRIBER = """
 UPDATE SUBSCRIBER
 SET NOTE = ?, UPDATE_DATE = DATETIME('NOW','LOCALTIME')
 WHERE USERNAME = ?
"""

DELETE_SUBSCRIBER = """
 DELETE FROM SUBSCRIBER
 WHERE USERNAME = ?
"""

CREATE_SCHEMA = """
 CREATE TABLE IF NOT EXISTS
 SUBSCRIBER (
 ID INTEGER PRIMARY KEY AUTOINCREMENT,
 USERNAME TEXT NOT NULL,
 NOTE TEXT,
 INPUT_DATE DATE,
 UPDATE_DATE DATE
 )
"""